# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Generate Release

on:
  push:
    branches:
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@2.0.0
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
      - run: npm version --message "Set Release version to ${{ env.GITHUB_REF_SLUG }}" ${{ env.GITHUB_REF_SLUG }}
      #- uses: stefanzweifel/git-auto-commit-action@v4
        #with:
          #commit_message: "Set Release version to ${{ env.GITHUB_REF_SLUG }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.GITHUB_REF_SLUG }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: "${{ env.GITHUB_REF_SLUG }}"
            release_name: Release "${{ env.GITHUB_REF_SLUG }}"
            body: |
              Changes in this Release
            draft: false
            prerelease: false

      - name: "Set next development version"
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
      - run: npm version --message "Set next development version" preminor --preid alpha
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
